djangoDiplomaProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from customer.views import customer
from main_page.views import main_page
from account.views import registration_view, login_view, logout_view

urlpatterns = [
    path('registration/', registration_view, name='registration'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),

    path('admin/', admin.site.urls),
    path('customer/', customer),
    path('', main_page),
    path('manager/', include('manager.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.urls import path
from .views import reservations_list, update_reservation

app_name = 'manager'

urlpatterns = [
    path('reservations/', reservations_list, name='reservations_list'),
    path('reservations/update/<int:pk>/', update_reservation, name='update_reserve')
]

manager/models.py
from django.db import models

# Create your models here.

manager/views.py
from django.shortcuts import render, HttpResponse, redirect
from main_page.models import UserReservation
from django.contrib.auth.decorators import login_required, user_passes_test

def is_manager(user):
    return user.groups.filter(name='manager').exists()

@login_required(login_url='/login/')
@user_passes_test(is_manager)
def reservations_list(request):
    reservations = UserReservation.objects.filter(is_processed=False)
    return render(request, 'reservations_list.html', context={
        'reservations': reservations,
    })

@login_required(login_url='/login/')
@user_passes_test(is_manager)
def update_reservation(request, pk):
    UserReservation.objects.filter(pk=pk).update(is_processed=True)
    return redirect('manager:reservations_list')

manager/templates/reservations_list.html
{% extends 'index.html' %}

{% block content %}
    <section id="reserves">
        <div class="container">
            <div class="col-md-10 col-md-offset-1">
                {% for item in reservations %}
                    <div class="row">
                        <div class="col-md-3">
                            <a href="{% url 'manager:update_reserve' pk=item.pk %}">
                                <button type="button" class="btn btn-primary">Table booked</button>
                            </a>
                        </div>
                        <div class="col-md-3">{{ item.name }}</div>
                        <div class="col-md-3">{{ item.email }}</div>
                        <div class="col-md-3">{{ item.phone }}</div>
                        <div class="col-md-3">{{ item.date|date:'d-m-Y' }}</div>
                        <div class="col-md-3">{{ item.time|time:'H:i' }}</div>
                        <div class="col-md-3">{{ item.number_people }}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-3"></div>
                        <div class="col-md-9"><p>{{ item.message }}</p></div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}